[package]
name = "steam-auto-gamemode"
version = "0.1.0"
authors = ["Diego Veralli <diegoov@gmail.com>"]
edition = "2018"

[dependencies]
x11rb = { version ="0.6.*", features = ["res"] }
dbus = "0.9.*"
ctrlc = { version = "3.*", features = ["termination"] }

[profile.release]
lto = true
