name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: rustup component add rustfmt
    - run: rustup component add clippy
    - run: sudo apt-get install -y --no-install-recommends jq libdbus-1-dev coreutils
    - name: Build
      run: ./build.sh check
